"""date_posted migrate

Revision ID: 54cb5c45aa77
Revises: 6a9e4c09abb7
Create Date: 2021-02-24 18:07:14.300439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cb5c45aa77'
down_revision = '6a9e4c09abb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
