"""edit_profile_migrate

Revision ID: 6f6fe3082f7f
Revises: 54cb5c45aa77
Create Date: 2021-02-25 17:26:56.455806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6fe3082f7f'
down_revision = '54cb5c45aa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('edit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'edit_count')
    # ### end Alembic commands ###
